In [1]:
import pandas as pd
import numpy as np
from google.colab import files
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD
from google.colab import drive
from joblib import dump

In [2]:
uploaded = files.upload()

df = pd.read_csv(next(iter(uploaded)))
df.head()

Saving yoga_program_ML_training_data.csv to yoga_program_ML_training_data.csv


pose_name    nose_x    nose_y    nose_z  left_shoulder_x  left_shoulder_y  \
0  cat pose -0.516661  0.129909 -0.040134        -0.456642         0.087930   
1  cat pose -0.439104  0.075872 -0.051650        -0.420443        -0.063529   
2  cat pose  0.416784  0.036046 -0.071157         0.431970        -0.062432   
3  cat pose  0.392603  0.035017 -0.025522         0.418557        -0.052292   
4  cat pose -0.400933  0.082890 -0.103624        -0.404127        -0.033562   

   left_shoulder_z  right_shoulder_x  right_shoulder_y  right_shoulder_z  ...  \
0        -0.150298         -0.559500         -0.048387          0.167710  ...   
1        -0.126287         -0.493098         -0.071897          0.195785  ...   
2         0.122458          0.469218         -0.058143         -0.100613  ...   
3         0.176311          0.476803         -0.051133         -0.068131  ...   
4        -0.184631         -0.523160         -0.068294          0.120899  ...   

   left_shoulder_hip_knee_angle  right_shoulder_hip_knee_angle  \
0                     90.383228                      95.917025   
1                     78.669241                      84.834516   
2                     75.142867                      91.846252   
3                     73.774703                      85.272324   
4                     80.949129                      89.740441   

   left_hip_knee_ankle_angle  right_hip_knee_ankle_angle  \
0                  94.432062                   91.495575   
1                  94.975611                   85.063283   
2                  82.242260                  102.820151   
3                  81.884197                   99.688948   
4                  96.669858                   95.909843   

   left_shoulder_elbow_wrist_angle  right_shoulder_elbow_wrist_angle  \
0                        58.989127                         47.994986   
1                        50.151370                         29.404093   
2                        11.712166                         36.841794   
3                        10.293739                         38.302575   
4                        46.580593                         24.952177   

   left_hip_shoulder_elbow_angle  right_hip_shoulder_elbow_angle  \
0                      80.646952                      112.963827   
1                      98.053367                      114.593382   
2                      83.740180                      104.608740   
3                      83.449668                      109.410328   
4                      88.362066                      105.823007   

   left_head_shoulder_hip_angle  right_head_shoulder_hip_angle  
0                     69.146791                     106.356016  
1                     95.507592                     116.206253  
2                     98.904615                     124.027859  
3                    107.042943                     133.637379  
4                    104.459171                     121.998540  

[5 rows x 50 columns]

In [3]:
class_name = df['pose_name'].unique()
print(class_name)

['cat pose' 'chair pose' 'corpse pose' 'cow pose' 'downward dog pose'
 'flat back pose' 'high lunge pose' 'knee to elbow plank pose'
 'knees to chest pose' 'low lunge pose' 'mountain pose'
 'runners lunge twist pose' 'seated spinal twist pose'
 'side plank yoga pose' 'standing forward bend pose' 'tabletop pose'
 'three legged dog pose' 'tip toe pose' 'tree pose' 'upper plank pose']


In [4]:
#assigning the values of the df to a numpy array
data=df.values

In [5]:
num_rows = data.shape[0]
num_cols = data.shape[1]

print(num_rows)
print(num_cols)

1496
50


In [6]:
features = data[:, 1:]
target = data[:, 0]

features = np.asarray(features).astype(np.float32)

In [7]:
#splitting test train sets features and labels
features_data_train, features_data_test, target_data_train, target_data_test = train_test_split(features, target, test_size=0.2, random_state=42, shuffle= True)

In [8]:
print("Shape of features_data_train:", features_data_train.shape)
print("Shape of features_data_test:", features_data_test.shape)
print("Shape of target_data_train:", target_data_train.shape)
print("Shape of target_data_test:", target_data_test.shape)

Shape of features_data_train: (1196, 49)
Shape of features_data_test: (300, 49)
Shape of target_data_train: (1196,)
Shape of target_data_test: (300,)


In [9]:
#scaling data
scaler = StandardScaler()
features_data_train = scaler.fit_transform(features_data_train)
features_data_test = scaler.transform(features_data_test)

In [10]:
label_encoder = LabelEncoder()
onehot_encoder = OneHotEncoder(sparse_output=False)

#encode labels
target_reshaped_train = label_encoder.fit_transform(target_data_train)
target_reshaped_test = label_encoder.transform(target_data_test)

#reshape target data for one-hot encoding
target_data_train = target_reshaped_train.reshape(-1, 1)
target_data_test = target_reshaped_test.reshape(-1, 1)

#one-hot encode the labels
target_data_train = onehot_encoder.fit_transform(target_data_train)
target_data_test = onehot_encoder.transform(target_data_test)

In [11]:
np.set_printoptions(threshold=np.inf)
print(target_data_test)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [12]:
#creating a list of labels from encoded labels/targets
# 0 -19 representing 20 poses
decoded = onehot_encoder.categories_
for i in decoded:
  label_list = i.tolist()
  print(label_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [13]:
#Model5 Keras Sequential
input_dim = features_data_train.shape[1]  #ensure the input dimension is correct
model_keras = Sequential()
model_keras.add(Dense(units=100, activation='relu', input_dim=input_dim))
model_keras.add(Dense(20, activation='softmax'))

model_keras.compile(optimizer=SGD(learning_rate=0.01, momentum=0.9),
                    loss='categorical_crossentropy',
                    metrics=['accuracy'])

model_keras.fit(features_data_train, target_data_train, batch_size=25, epochs=100)

Epoch 1/100
48/48 [==============================] - 1s 3ms/step - loss: 2.0614 - accuracy: 0.4390
Epoch 2/100
48/48 [==============================] - 0s 3ms/step - loss: 0.7638 - accuracy: 0.8612
Epoch 3/100
48/48 [==============================] - 0s 3ms/step - loss: 0.4473 - accuracy: 0.9156
Epoch 4/100
48/48 [==============================] - 0s 3ms/step - loss: 0.3251 - accuracy: 0.9331
Epoch 5/100
48/48 [==============================] - 0s 3ms/step - loss: 0.2573 - accuracy: 0.9465
Epoch 6/100
48/48 [==============================] - 0s 4ms/step - loss: 0.2097 - accuracy: 0.9615
Epoch 7/100
48/48 [==============================] - 0s 3ms/step - loss: 0.1799 - accuracy: 0.9657
Epoch 8/100
48/48 [==============================] - 0s 3ms/step - loss: 0.1553 - accuracy: 0.9699
Epoch 9/100
48/48 [==============================] - 0s 3ms/step - loss: 0.1372 - accuracy: 0.9716
Epoch 10/100
48/48 [==============================] - 0s 3ms/step - loss: 0.1212 - accuracy: 0.9774
Epoch 11/

In [14]:
predictions= model_keras.predict(features_data_test)

10/10 [==============================] - 0s 2ms/step


In [15]:
loss, accuracy = model_keras.evaluate(features_data_test, target_data_test)
print(f"Test Accuracy: {accuracy * 100:.2f}%")

10/10 [==============================] - 0s 3ms/step - loss: 0.1676 - accuracy: 0.9633
Test Accuracy: 96.33%


In [16]:
keras_model_results = []
for i in range(len(predictions)):
  arr = predictions[i]
  max_val = max(arr)
  predicted_val = class_name[np.argmax(predictions[i])]

  coded_label_list= list(target_data_test[i])
  max_val_index = coded_label_list.index(max(coded_label_list))
  label_val = class_name[max_val_index]

  formatted_percentage_output = [round(value * 100) for value in arr]
  formatted_percentage_output.append(predicted_val)
  formatted_percentage_output.append(label_val)
  if predicted_val == label_val:
    formatted_percentage_output.append('YES')
  else:
    formatted_percentage_output.append('NO')

  keras_model_results.append(formatted_percentage_output)


In [ ]:
from google.colab import files
keras_df = pd.DataFrame(keras_model_results, columns= ['cat pose','chair pose','corpse pose','cow pose','downward dog pose','flat back pose','high lunge pose',\
                                                   'knee to elbow plank pose','knees to chest pose','low lunge pose','mountain pose','runners lunge twist pose',\
                                                   'seated spinal twist pose','side plank yoga pose','standing forward bend pose','tabletop pose','three legged dog pose',\
                                                   'tip toe pose','tree pose','upper plank pose','predicted label','true label','accurate'])
keras_df.to_csv('keras_model_results.csv', index=False)

files.download('/content/keras_model_results.csv')

In [17]:
drive.mount('/content/drive')
model_keras.save('/content/drive/My Drive/Model5_Keras.h5')

Mounted at /content/drive


/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
